version: '3'
services:
    database:
        build: ./init/mysql
        container_name: orders
        restart: always
        tty: true
        environment:
            MYSQL_DATABASE: 'app'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "3306:3306"
        volumes:
            - ./init:/docker-entrypoint-initdb.d
            - ./init/mysql/dbdata:/var/lib/mysql




