version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    database:
        build: ./mysql
        container_name: orders
        restart: always
        tty: true
        environment:
            MYSQL_DATABASE: 'app'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/.dbdata:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - ./mysql/.redis:/data
        networks:
            - laravel

#    frontend: # ainda nao funciona
#        build: ./node
#        container_name: frontend
#        volumes:
#            - ./frontend:/app
#        ports:
#            - "8080:8080"
#        command: ['npm', 'run', 'serve']
#        networks:
#            - laravel

networks:
    laravel:
        driver: bridge




